name: "develop - Deploy infra"

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: write
  #issues: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-east-1"
  PULUMI_STACK: dev
  ENVIRONMENT: develop
  S3_BUCKET_PULUMI_STATE: "develop-test-llm-pulumi-state"


  


jobs:
  setup-and-preview:
    name: "Setup and preview"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac-lab2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
  
      # Installs the Pulumi CLI.
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2

      # Pulumi login
      - name: Pulumi login
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # Init the appropriate stack.
      - name: List Pulumi stacks
        run: pulumi stack ls

      # Select the appropriate stack.
      - name: Select Pulumi stack
        run: pulumi stack select $PULUMI_STACK

      - name: Install dependencies
        run: pip install -r requirements.txt
     
      # List files
      - name: List files
        run: ls -ltr

      - name: aws creds
        run: aws configure list-profiles
      
      # List files
      - name: List files
        run: ls -ltra $HOME

      # Select the appropriate stack.
      - name: Pulumi preview
        run: pulumi preview

      ## https://github.com/pulumi/actions
      #- uses: pulumi/actions@v5
      #  with:
      #    command: preview
      #    stack-name: $PULUMI_STACK
      #  env:
      #    PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      #- name: Login to S3 for state management
      #  run: |
      #    pulumi login s3://$S3_BUCKET_PULUMI_STATE
      #
      #- name: Create Pulumi Stack
      #  #run: pulumi stack init ${PULUMI_STACK} --secrets-provider="awskms://${{ env.AWS_KMS_KEY_ID }}"
      #  run: pulumi stack init $PULUMI_STACK
      #  continue-on-error: true
      #
      #- name: Select Pulumi Stack
      #  #run: pulumi stack select ${PULUMI_STACK} --secrets-provider="awskms://${{ env.AWS_KMS_KEY_ID }}"
      #  run: pulumi stack select $PULUMI_STACK
      #
      #- name: Run a plan
      #  run: | 
      #    #pulumi stack change-secrets-provider "awskms://${{ env.AWS_KMS_KEY_ID }}"
      #    pulumi stack change-secrets-provider
      #    pulumi preview
